# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Red Hat
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
---
- name: Suse | Install package dependencies
  zypper:
    name: docker.io
    state: present

- name: Suse | Install docker-compose
  pip:
    name: docker-compose>=1.29
    state: present
